#!/bin/bash

# Combine Schemas Script
# Combines all schema files into a single SQL file for easy copy-paste
#
# Usage:
#   ./supabase/scripts/combine-schemas.sh
#   ./supabase/scripts/combine-schemas.sh 06 07  # Combine specific schemas

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMAS_DIR="$SCRIPT_DIR/../schemas"
OUTPUT_FILE="$SCRIPT_DIR/../combined-schema.sql"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔═══════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Combine Schema Files                ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════╝${NC}"
echo ""

# Determine which schemas to combine
if [ $# -eq 0 ]; then
    SCHEMA_FILES=("$SCHEMAS_DIR"/*.sql)
else
    SCHEMA_FILES=()
    for num in "$@"; do
        found_files=("$SCHEMAS_DIR"/${num}_*.sql)
        if [ -e "${found_files[0]}" ]; then
            SCHEMA_FILES+=("${found_files[@]}")
        fi
    done
fi

# Sort schema files
IFS=$'\n' SCHEMA_FILES=($(sort <<<"${SCHEMA_FILES[*]}"))
unset IFS

echo -e "${GREEN}📦 Combining ${#SCHEMA_FILES[@]} schema file(s):${NC}"
for file in "${SCHEMA_FILES[@]}"; do
    echo "   - $(basename "$file")"
done
echo ""

# Clear output file
> "$OUTPUT_FILE"

# Add header
cat >> "$OUTPUT_FILE" << 'EOF'
-- =====================================================
-- AGILSPACE DATABASE SCHEMA
-- =====================================================
-- This file is auto-generated by combining all schema files.
-- Apply this in your Supabase SQL Editor to set up the database.
--
-- Generated at:
EOF

echo "-- $(date)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Combine all schema files
for schema_file in "${SCHEMA_FILES[@]}"; do
    filename=$(basename "$schema_file")

    echo "-- =====================================================" >> "$OUTPUT_FILE"
    echo "-- FILE: $filename" >> "$OUTPUT_FILE"
    echo "-- =====================================================" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

    cat "$schema_file" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

echo -e "${GREEN}✅ Combined schema created: ${OUTPUT_FILE}${NC}"
echo ""
echo "You can now:"
echo "1. Open the file: ${OUTPUT_FILE}"
echo "2. Copy all contents"
echo "3. Paste into Supabase SQL Editor"
echo "4. Execute"
echo ""

# Try to copy to clipboard if available
if command -v pbcopy &> /dev/null; then
    cat "$OUTPUT_FILE" | pbcopy
    echo -e "${GREEN}📋 Schema copied to clipboard (macOS)!${NC}"
elif command -v xclip &> /dev/null; then
    cat "$OUTPUT_FILE" | xclip -selection clipboard
    echo -e "${GREEN}📋 Schema copied to clipboard (Linux)!${NC}"
elif command -v clip &> /dev/null; then
    cat "$OUTPUT_FILE" | clip
    echo -e "${GREEN}📋 Schema copied to clipboard (Windows)!${NC}"
fi

echo ""
